sudo: required
language: generic

services:
  - docker

script:
  - wget -O- http://travis.debian.net/script.sh | sh -

if:
  tag IS blank

env:
  - TRAVIS_DEBIAN_DISTRIBUTION=Kicksecure
  - TRAVIS_DEBIAN_DISTRIBUTION=buster
  - TRAVIS_DEBIAN_SECURITY_UPDATES=true
  - TRAVIS_DEBIAN_GIT_BUILDPACKAGE=./usr/share/hardened-vm-kernel/ci_test
  - TRAVIS_DEBIAN_GIT_BUILDPACKAGE_OPTIONS=""
